### ISSUE TITLE
how do i change horizontal recoil

### ISSUE THREAD

**Issue by pipvid** [Harry-Hopkinson/R6-No-Recoil#12]
how do i change horizontal recoil

**Comment by Harry-Hopkinson** [comment]
Edit this section of the Config.toml that should be generated in the directory where the exe is ran.

```toml
# Horizontal recoil amounts for each preset
LowSensHorizontal = 0
MediumSensHorizontal = 0
HighSensHorizontal = 0
UltraSensHorizontal = 0
```

Then reload the tool and there should be horizontal recoil.
